repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        # Include submodules
        exclude: |
            (?x)^(
                .*/\.git/
            )$
        # Enable submodule traversal
        always_run: true
    -   id: end-of-file-fixer
        exclude: |
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-toml

# Python formatting - auto-fixes without failing
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args: [--line-length=88]
        exclude: commune-ipfs/

# Python linting - auto-fixes without failing
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
    -   id: ruff
        args: [--fix, --exit-zero]
        exclude: commune-ipfs/

# Python import sorting - auto-fixes without failing
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: [--profile=black]
        exclude: commune-ipfs/

# Rust tooling - simplified to avoid failures
-   repo: local
    hooks:
    -   id: rustfmt
        name: rustfmt
        entry: rustfmt
        language: system
        types: [rust]
        exclude: commune-ipfs/
