name: Python CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: |
          cd commune-ipfs
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install -e .

      - name: Run Black
        run: |
          cd commune-ipfs
          source .venv/bin/activate
          black . --check

      - name: Run isort
        run: |
          cd commune-ipfs
          source .venv/bin/activate
          isort . --check-only --profile black

      - name: Run Ruff
        run: |
          cd commune-ipfs
          source .venv/bin/activate
          ruff check .

      - name: Run MyPy
        run: |
          cd commune-ipfs
          source .venv/bin/activate
          mypy app/ --ignore-missing-imports

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: |
          cd commune-ipfs
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install -e .

      - name: Run tests
        run: |
          cd commune-ipfs
          source .venv/bin/activate
          pytest tests/ -v --cov=app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Bakobiibizo/commune-ipfs
