name: Python CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/python.yml'

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest black isort

      - name: Run Black
        run: black . --check
        
      - name: Run isort
        run: isort . --check-only --profile black
        
      - name: Run Ruff
        run: ruff check .
        
      - name: Run MyPy
        run: mypy .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
